
export const home = '/home'
export const signup = '/signup'
export const login = '/login'
export const dashboard = '/dashboard'
export const profile = '/profile'
export const editprofile = '/edit-profile'
export const notifications = '/notifications'
export const messages = '/messages'
export const chat = '/chat'
export const search = '/search'
export const followers = '/followers'
export const following = '/following'
export const compose = '/compose'
export const postpage = '/postpage'
export const users = '/users'
export const todo = '/todo'